# Generated by Django 6.0.7 on 2026-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appid", models.IntegerField(unique=True, verbose_name="ID игры")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "developer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Разработчик"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Издатель"
                    ),
                ),
                (
                    "owners",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Владельцы (диапазон)"
                    ),
                ),
                (
                    "ccu",
                    models.IntegerField(default=0, verbose_name="Пиковый онлайн (CCU)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
                "ordering": ["-ccu"],
            },
        ),
    ]
